steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-python-app:$COMMIT_SHA'
    - '.'

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-python-app:$COMMIT_SHA'

# 3. Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  id: Deploy
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - 'my-python-app'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-python-app:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--quiet'