apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        # Cloud Build will automatically replace the image tag during deployment
        image: us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-gke-app:latest
        ports:
        - containerPort: 5000 # This must match the port exposed in the Dockerfile
